name: CI
on:
  pull_request:
    branches:
      - develop
      - master
  push:
  workflow_dispatch:

jobs:
  test:
    env:
      INFURA_API_KEY: a6820824c76c4458af1d67599e3d5f7c #TODO change to ${{ secrets.INFURA_API_KEY }}
      ETHERSCAN_API_KEY: C5FMJWYPA4EN2DEHVSDRIQRTDKF5279AH8 #TODO change to ${{ secrets.INFURA_API_KEY }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --global yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test